### ISSUE TITLE
Raycasting on moving objects

### ISSUE THREAD

**Issue by gaschavardes** [oframe/ogl#101]
Hi ! 
I would like to create some mouse interactions on several moving planes and for that I need to know which planes I'm hovering. I've implemented the Raycasting method like in your example [here ](https://github.com/oframe/ogl/blob/master/examples/raycasting.html) but it seems like I'm hovering all my planes in the center of the canvas, just like if the raycasting method wasn't considering my position.set() modifications.
Is there a way around that ? Or I'm I doing something wrong ? 
Thanks a lot !

**Comment by gordonnl** [comment]
Hi, could you please make a https://codesandbox.io/ or https://codepen.io/ with the issue?

You can reply here, however I just wanted to note that individual help would be best suited on https://stackoverflow.com/questions/tagged/ogl

**Comment by gaschavardes** [comment]
Hi ! Thank you for your answer !
Ok I will create a topic on stackoverflow then !
See you there

**Comment by gaschavardes** [comment]
Hi !
I created a question [here](https://stackoverflow.com/questions/67301123/raycasting-on-moving-objects) 
Thank you !
