### ISSUE TITLE
KHR_parallel_shader_compile extension support

### ISSUE THREAD

**Issue by hansagames** [oframe/ogl#102]
Hi,
what about adding support for this [extension](https://developer.mozilla.org/en-US/docs/Web/API/KHR_parallel_shader_compile) ?
[support](https://caniuse.com/mdn-api_khr_parallel_shader_compile) looks quite decent

this would speed up compilation of app with lot of materials as they could be added in parallel not in sequence.

also some more examples [here](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices)

**Comment by gordonnl** [comment]
From my understanding, it will no speed up compilation, it merely allow asynchronous polling of the shader link status. Quote "you can check the status of your shaders compiling without blocking the runtime".

**Comment by eXponenta** [comment]
This is speedup, shader compilation is async, but grab their status is require GPU syncing, and sync will wait while shader wasn't be compiled.
If there are more that 2 different shaders - this can be performance stall.
But for this required a asynchronious render pipeline, because you can't do nothing with material while is is not complite.

**Comment by gordonnl** [comment]
From the documentation, it is only a speed up for those polling the compile/link status.

From the [spec](https://www.khronos.org/registry/webgl/extensions/KHR_parallel_shader_compile/)
> Notes: Implementations are free to optimize shader compilation and program linking via concurrency with or without this extension, but without this extension, there is no way for a user to check compile/link status without potentially blocking and stalling until the result of compilation/linking is known.

The polling of shaders isn't something most people need to do, so in these cases, I would recommend just installing the extension yourself - i.e. there is little benefit of OGL handling this, it's one line.

```
const ext = gl.getExtension('KHR_parallel_shader_compile');
```
