### ISSUE TITLE
PBR examples using incorrect normals

### ISSUE THREAD

**Issue by RAX7** [oframe/ogl#105]
I found two examles with PBR rendering:
[First one](https://oframe.github.io/ogl/examples/?src=pbr.html) using normal in view space: `normalize((vec4(normal, 0.0) * viewMatrix).xyz)`.
[Second](https://oframe.github.io/ogl/examples/?src=load-gltf.html) using world space: `normalize(vNormal)`.
Both way giving weird result. First way is glitching on diffuse light, and second one on specular light. 
I think I found a solution: for diffuse should be used normals in world space, and for specular in view space.
[Here is demo](https://codepen.io/RAX7/pen/rNyzRZj). Am I correct or the reason is something else?

**Comment by repalash** [comment]
Both the examples are using world space. 
In the first one, the `normal` is multiplied by the `normalMatrix` which is basically `transpose(inverse(modelViewMatrix))`. So when you do `normalize((vec4(normal, 0.0) * viewMatrix).xyz)`, you get world space normal. This is skipped in the 2nd example as I guess there is just one model.

In your code, you can remove normalMatrix multiplication or just do it like the first example.

**Comment by RAX7** [comment]
> Both the examples are using world space.

Yes, you're right, I was totally wrong.
But I still have issue. If I remove normalMatrix multiplication in vertex shader and get normal like: `vec3 N = normalize(vNormal)` and after what apply some transformation in js, like: `sphereMesh.rotation.y += 0.005;` then lighting become incorrect
![111](https://user-images.githubusercontent.com/10919192/120105243-4f94e780-c182-11eb-9c86-e91576bc3d19.gif)
In over way, if I apply normalMatrix in vertex shader and get it back in world space in fragment shadrer, then I have noize glitches on top of cube side
![222](https://user-images.githubusercontent.com/10919192/120105498-5cfea180-c183-11eb-84a8-79da50c2253d.gif)
I suppose reason of noise is floating-point error then doing `normalize((vec4(normal, 0.0) * viewMatrix).xyz)` an after that ising this vec3 in `atan(n.z, n.x)`.
What is way should I use to get right transforms on mesh and clear light without noise?

**Comment by repalash** [comment]
Actually, it's better to do the calculation directly in view space. Here `-viewPos` is the view direction.
I have updated your codepen here: https://codepen.io/repalash/pen/NWpwXQr

**Comment by RAX7** [comment]
Perfect! It's took two days to try fix this by my self. I think this way shoud be using in all OGL examples, because other ways are confusing in some edge cases. Thank you!
