### ISSUE TITLE
Multiple canvas on same page

### ISSUE THREAD

**Issue by MrBushid0** [oframe/ogl#114]
Sorry, not sure if this is an issue per se but thought I'd ask here since I couldn't get any pointers on SO

I just started using OGL and made a simple slider as a class to test it out. It works great but if I try to use more than one slider on the same page, only one plane shows on the page. I don't see any errors and the code runs for all sliders on the page but only one plane gets shown on the page at any one time.

I put in a quick sandbox here https://codesandbox.io/s/ogl-multiple-canvas-37mpu?file=/slider.js to show the "problem".

I'm not sure if the problem is with my implementation or if OGL is only meant to have 1 canvas at any one point. 

Thank you for the beautiful lib!

**Comment by hansagames** [comment]
Multiple canvas is quite nasty feature, especially if input event should be supported. What you can do is to make new OGL Redner for each canvas, but would not suggest if you have many, also remember there is limit of WebGL contexts what can be created at same time, and some older browsers have quite low limits

**Comment by MrBushid0** [comment]
Thanks!

Yeah I know there is a limit of how many contexts can be created at the browser level and I'd usually have just one canvas per page but in this case, it's for a widget to be used with a page builder on WordPress and some users might want to have more than one on the same page. 

For the example above, every separate slider has its own renderer etc. I think the problem is with the positioning part of the plane. the simple solution I found is to do the same thing curtainsjs does, 

Instead of creating a canvas that spans the whole viewport every time and then a plane with the image dimension, I instead create the canvas and the plane with the dimensions of images, and then inject the canvas beneath the image container.  Seems to work ok this way.

**Comment by gordonnl** [comment]
It seems to be an issue with your layout. If I scroll down a bit and resize, it will try to re-draw the images incorrectly.
Perhaps keep the canvases the size of your images rather than full screen?
Sorry unfortunately I can't give individual project feedback on here, and couldn't see a quick fix to your problem.
Best of luck!

**Comment by MrBushid0** [comment]
@gordonnl Thanks. Yeah, that's exactly what I ended up doing, the canvases and planes use the size of the images

No worries, thanks for looking it up. Appreciate all the work you put in this lib!
