### ISSUE TITLE
Attributes in shader | Example of simple texture shader/mesh

### ISSUE THREAD

**Issue by gen4sp** [oframe/ogl#115]
I want to draw a simple mesh (triangle?) with a texture on it.
The goal is to add the image instead of animated cubes in the Post Fluid Distortion example ()
I use the following shaders:
Vertex
```
const tvertex = /* glsl */ `
precision highp float;
attribute vec4 aVertexPosition;
attribute vec2 aTextureCoord;

uniform mat4 uModelViewMatrix;
uniform mat4 uProjectionMatrix;

varying highp vec2 vTextureCoord;

void main(void) {
  gl_Position = uProjectionMatrix * uModelViewMatrix * aVertexPosition;
  vTextureCoord = aTextureCoord;
} `
```

Fragment:
```
const tfragment = /* glsl */ `
precision highp float;
vec2 vTextureCoord;

uniform sampler2D uSampler;

void main(void) {
  gl_FragColor = texture2D(uSampler, vTextureCoord);
}
            `
```

And following code to draw:
```
const p11 = new Program(gl, {
    vertex: tvertex,
    fragment: tfragment,
    uniforms: {
      uSampler: { value: baseTexture }
    }
  })

const mesh = new Mesh(gl, {
    geometry: new Triangle(gl),
    program: p11
  })

  const pass = post.addPass({
    fragment,
    uniforms: {
      tFluid: { value: null },
      uTime: { value: 0 }
    }
  })
```

It gives me the following error: 
```
Program.js?82c4:302 Active uniform uModelViewMatrix has not been supplied
Program.js?82c4:302 Active uniform uProjectionMatrix has not been supplied
Geometry.js?56f1:133 active attribute aVertexPosition not being supplied
Geometry.js?56f1:133 active attribute aTextureCoord not being supplied

```
Could you help me with an example or give a hint, what is the right and best way to do it?
Thank you!

**Comment by gordonnl** [comment]
Sorry for the delay!
When you create a geometry using the helper classes (eg `Triangle`) it will create the attributes in a specific format that you then need to match in your vertex shader.

```
attribute vec4 aVertexPosition;
attribute vec2 aTextureCoord;
```
is currently expecting attributes called `aVertexPosition` as a `vec4` and `aTextureCoord` as a `vec2`, which doesn't match the [Triangle class](https://github.com/oframe/ogl/blob/master/src/extras/Triangle.js).

Have a look at the Triangle Screen Shader example for how to use this geometry type in the vertex shader.
https://github.com/oframe/ogl/blob/71a78904e855aa97920188d38362507e7116a4e7/examples/triangle-screen-shader.html#L20-L30
