### ISSUE TITLE
Ogl with nuxt 🙃

### ISSUE THREAD

**Issue by josuemartinezz** [oframe/ogl#117]
I was recently trying to integrate ogl with nuxt, what I did was import through a plugin:

In the following route: `plugins/ogl.client.js`

```
import ogl from 'ogl'

export default (context, inject) => {
  inject('ogl', ogl)
}
```

In my: `nuxt.config.js`

`plugins: ['@/plugins/ogl.client.js'],`

I am trying to inject to the nuxt context, everything is done correctly, until the following error appears:

```
ERROR in ./node_modules/ogl/src/index.mjs 42:0-52
Can't reexport the named export 'GLTFLoader' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ogl/src/extras/GLTFLoader.js 86:36
Module parse failed: Unexpected token (86:36)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         if (desc.asset === undefined || desc.asset.version[0] < 2) console.warn('Only GLTF >=2.0 supported. Attempting to parse.');
| 
>         if (desc.extensionsRequired?.includes('KHR_texture_basisu') && !this.basisManager)
|             console.warn('KHR_texture_basisu extension required but no manager supplied. Use .setBasisManager()');
| 
```

Any solution? 🤔

**Comment by gordonnl** [comment]
Sorry I'm unfamiliar with the Nuxt bundling pipeline. I'll leave this open for a while in case someone else can help you out!

**Comment by CodyJasonBennett** [comment]
You'll need to configure a Webpack loader to handle `.mjs` and transpile it if your environment does not support ESM or ES6 modules (Node will expect CJS by default). See [Nuxt's transpile option](https://nuxtjs.org/docs/configuration-glossary/configuration-build/#transpile).

From what I understand, Nuxt will support ESM OOTB with `type="module"` in your package.json: https://github.com/nuxt/nuxt.js/issues/1935.

**Comment by josuemartinezz** [comment]
The way how to solve it was the following:

In my file `nuxt.config.js`
```
  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    transpile: ['ogl'],
  },
```
