### ISSUE TITLE
Renderer size on Android cannot be larger than 4096px?

### ISSUE THREAD

**Issue by zlac** [oframe/ogl#126]
I am facing an issue on Android 10, Chrome 98.0.4758.87 and on stock browser. 

Here is the example https://codepen.io/creativeinteractivemedia/pen/ZEaaoMO

On desktop everything works fine, for any renderer size, the plane is always in top left corner.

On Android, if renderer height is greater than 4096px, the scene becomes stretched.  If renderer.dpr is used, then renderer size cannot be greater than 4096 / renderer.dpr. 

Thanks

**Comment by eXponenta** [comment]
because there are a limits on texture and viewport
for different devices is different.

Some low end phones not allow viewport more that 4096

https://webglreport.com/?v=2

**Comment by zlac** [comment]
Thanks!
