### ISSUE TITLE
transparency 

### ISSUE THREAD

**Issue by zlac** [oframe/ogl#129]
Thanks for the awesome job with this library! 

I have a problem with transparent canvas and transparent objects. Here is an example 

https://codepen.io/creativeinteractivemedia/pen/NWwMpYX

Semi transparent object (red plane with alpha 0.5) is over a non transparent object ( blue plane with alpha 1), the blue plane behind become transparent, on the part where is covered by red plane. 

<img width="451" alt="Screenshot 2022-02-21 at 22 38 42" src="https://user-images.githubusercontent.com/2691276/155029188-91a3542a-d7fe-4e4c-8ef8-f2f4b4a7547e.png">

Any idea how to fix this? 

Thanks

**Comment by eXponenta** [comment]
Because canvas should be PMA

use a:
```
const renderer = new Renderer({ dpr: 2, alpha: true, premultipliedAlpha: true });
```

and you should know that in PMA mode all shader and blending should be in PMA too.
this means that you should multiple rgb onto a

**Comment by zlac** [comment]
Awesome, thanks much for your fast reply :)
