### ISSUE TITLE
TypeScript declarations

### ISSUE THREAD

**Issue by TiagoCavalcante** [oframe/ogl#135]
I think that TypeScript declarations are very important for any npm library, with TS 4.6 it can be done mostly automatically.

You can follow the `rollup.config.js` and `tsconfig.json` of [this repo](https://github.com/TiagoCavalcante/react-library-template) to generate the .d.ts files.

**Comment by hansagames** [comment]
Hi, @TiagoCavalcante 
could you please make PR with changes needed ?

**Comment by CodyJasonBennett** [comment]
That rollup config assumes the project is written in TypeScript.

**Comment by TiagoCavalcante** [comment]
@CodyJasonBennett my plan was to change all extensions to ts and fix the errors, but if you prefer I can add JSDoc. Out of the file declarations are error prone.

So what do you prefer?

**Comment by TiagoCavalcante** [comment]
@CodyJasonBennett my plan was to change all extensions to ts and fix the errors, but if you prefer I can add JSDoc. Out of the file declarations are error prone.

So what do you prefer?

**Comment by CodyJasonBennett** [comment]
I'd have to defer this to #24 where this was already discussed.

**Comment by TiagoCavalcante** [comment]
I didn't read that before, I'll only do it when you are sure if you want TS, I don't want to work on a rejected PR.

**Comment by gordonnl** [comment]
There are currently at least one TS fork of the library https://github.com/oframe/ogl/issues/24#issuecomment-822963673
I would recommend offering your support there. I'll add a link to the fork in the readme for other TS users. Thanks!

**Comment by pschroen** [comment]
I think the OP is more about the declarations rather than the code itself being written in TypeScript?

Here's the thread on what three.js has done for comparison:
https://discourse.threejs.org/t/with-r126-typescript-type-declaration-files-are-located-at-definitelytyped/23157
