### ISSUE TITLE
Tiny error on program removal

### ISSUE THREAD

**Issue by dekdevy** [oframe/ogl#14]
Tiny error. These two lines during the removal of a program are missing a `this.`

https://github.com/oframe/ogl/blob/210d69cd4ba06419a9f27ce5d89d1ae0dfdf0693/src/core/Program.js#L253-L254

**Comment by gordonnl** [comment]
Thanks for that catch. I actually removed them as those shaders are already deleted right after completion. I forgot to tag this issue in my commit, but it should be fixed now.

**Comment by dekdevy** [comment]
Oh, okay. I only got some errors, didn't realize they were already deleted; thank you for the fix!
