### ISSUE TITLE
Consider WebGPU implementation 

### ISSUE THREAD

**Issue by flyingzl** [oframe/ogl#146]
WebGPU is on the road,althogh it's still a W3C  Draft , but all the  browser vendors  are positive about it  and  it  seems a  good replacement or next  generation  for  WebGL,    how about staring  a WebGPU  implementation?

**Comment by flyingzl** [comment]
Oh, great!!   [https://github.com/oframe/ogpu](https://github.com/oframe/ogpu) seems under development now...

**Comment by gordonnl** [comment]
Unlike Threejs, OGL is tightly coupled to WebGL as a means for simplicity and brevity. So in the future if I do eventually tackle WebGPU it will indeed be in that repo, and this repo will remain targeting WebGL.

**Comment by gordonnl** [comment]
I'm keen to dig in when time permits, but no solid plans as of yet, sorry.
