### ISSUE TITLE
Is there any way to have a callback or promise resolved once a texture loads?

### ISSUE THREAD

**Issue by shampliu** [oframe/ogl#16]
I'm implementing a VideoTexture on a Plane but I'm running into a race condition where my scene tries to render before the Texture is loaded so the Plane is black.

**Comment by gordonnl** [comment]
Hey, thanks for the feedback. 

For this library, I'm leaving out a lot of the extras that you'd find in larger libraries (threejs etc) that don't concern WebGL directly (asset loading, audio, gamepad controls etc), so for this I'd recommend running your own implementation.

As an example, here's the image loading helper function I used in the [PBR Example](https://oframe.github.io/ogl/examples/?src=pbr.html)
```
            const textureCache = {};
            function getTexture(src, generateMipmaps = true) {
                if (textureCache[src]) return textureCache[src];
                const texture = new Texture(gl, {generateMipmaps});
                const image = new Image();
                textureCache[src] = texture;
                image.onload = () => {
                    texture.image = image;
                };
                image.src = src;
                return texture;
            }
```

Hope that helps!
