### ISSUE TITLE
Package json update broke mocks for jest

### ISSUE THREAD

**Issue by hansagames** [oframe/ogl#160]
Hi,
noticed that this update broke may jest based unit tests https://github.com/oframe/ogl/commit/363939c60d660f63928400faedb86370bce1d308

there `main` was removed and `exports` was added instead.
Trying to investigate more but after this change I can not mock `ogl` model in `jest` based unit tests.

Any reason it was removed ?

Thanks you

**Comment by hansagames** [comment]
Ok found this https://github.com/oframe/ogl/pull/138 where it was discussed

**Comment by hansagames** [comment]
Looks like it was fixed in jest 28, but I still have 26 will check if can upgrade

**Comment by gordonnl** [comment]
Closing for now, but please let me know if there's a solution that works in junction with the discussion in #138 . As I said there, I'm happy to change if it works everywhere.
