### ISSUE TITLE
Orthographic Camera does not set any bounds by default.

### ISSUE THREAD

**Issue by Cosmic-Goat** [oframe/ogl#162]
First of all, thanks for the wonderful library!

From looking at previous issues, it seems like the Orthographic Camera is supposed to have default bounds of `{left: -1, right: 1, top: 1, bottom: -1}`, but these are not set by default in the [source](https://github.com/oframe/ogl/blob/fadf0f39795d08ed52d45b4228a7550a80efc467/src/core/Camera.js#L10), resulting in the Orthographic Camera not working as expected unless explicitly passing in these parameters (calling 'camera.orthographic()` with no parameters will not display anything).

Since there are no examples using the orthographic camera and the library is completely undocumented, it's a little difficult to figure out exactly what you're supposed to give as options to `camera.orthographic()` (actually, [CodyJasonBennett's wonderful type declarations](https://github.com/CodyJasonBennett/ogl-types) for TypeScript have been quite helpful for figuring out how to use this library - I hope they will get official support). If no documentation or typings are going to be made, I feel that at least setting default values so that you can call functions and they 'just work' as expected would be nice and save a lot of trouble having to dig through source code and debugging. Would you consider adding default bounds to the Orthographic Camera?

**Comment by gordonnl** [comment]
Hey, thanks a lot!

You're right, we're definitely missing an example/documentation for using the orthographic camera. The only current usage in the examples is to generate a shadow map in the [ShadowMaps](https://oframe.github.io/ogl/examples/?src=shadow-maps.html) example.

I have added the defaults when calling `camera.orthographic()`, however I wouldn't say confidently that the orthographic camera is supposed to have default value of -1 to 1, especially if you're hoping to use it as a final render source (will need to match canvas size ratio). I tried to simplify the API in that you can just call eg `const camera = new Camera(gl, { left: -1, right: 1, bottom: -1, top: 1 });` and it would automatically apply an orthographic matrix calculation, in contrast to passing in an 'fov' for a perspective matrix, which is the default.

With the update however, it's possible to generate a quick 'default' orthographic camera by calling `const camera = new Camera(gl).orthographic()` without passing any arguments.

**Comment by monolithMktg** [comment]
Thank you for the hard work on OGL, Gordon!
I was researching about Ortho in OGL when I saw this post of yours. :D

Please keep the library updated. This is a treasure and easier than Regl.
