### ISSUE TITLE
Indexed Draw Offset multiplier is hardcoded to 2

### ISSUE THREAD

**Issue by nbouteme** [oframe/ogl#163]
https://github.com/oframe/ogl/blob/796a8fb600416e1479bdacb7bf0ad3feee733d37/src/core/Geometry.js#L196

It should be a multiple of the index attribute size, which could be a gl.UNSIGNED_INT of size 4.
This makes range draws on indexed buffers fail for larger buffers which require int indices.

**Comment by gordonnl** [comment]
Thanks for this!
The commit [17bc3ef](https://github.com/oframe/ogl/commit/17bc3efbddc0afcb002ea91fc6f108a74f126de1) hopefully addresses the issue.
Do you happen to have a mesh using `UNSIGNED_INT` to test with? 
The commit is included in version `0.0.110`

**Comment by nbouteme** [comment]
Unfortunately my use case was on generated geometry (points on a curve that are triangulated with earcut) so I don't have a loadable mesh for this.
But the patch looks good, thank you!
