### ISSUE TITLE
Intersect mesh state

### ISSUE THREAD

**Issue by willybrauner** [oframe/ogl#164]
Hi! I'm trying to get an updated intersect meshes array when a mesh intersect with another one. After digging through the OGL sources, I do not find a method to do this check. 

I reproduce a minimal example of this case witch not work with `raycast.intersectMeshes` method. (definitely i missed something about this one)
https://codesandbox.io/s/ogl-mesh-intersect-example-6s2mcp?file=/src/index.ts

For comparison, I also reproduced this case with threejs who provide the`intersectBox` method on the vector 3. The intersect state is update as needed.
https://codesandbox.io/s/three-intersect-example-nuejk8?file=/src/index.ts:0-1245

Is there a way to achieve this as `mesh1.intersectWith(mesh2)` with ogl, or another pattern which would allow to get this updated state?

**Comment by gordonnl** [comment]
Did you manage to find a solution in the end?

**Comment by willybrauner** [comment]
Unfortunately I did not easily manage to cover this feature with ogl. Thanks anyway!
