### ISSUE TITLE
How to make pipe geometry?

### ISSUE THREAD

**Issue by caracal7** [oframe/ogl#165]
Like cylinder but with hole inside

**Comment by gordonnl** [comment]
There is no geometry helper currently for creating a pipe, sorry!

**Comment by caracal7** [comment]
I took a close look at the [Cylinder.js](https://github.com/oframe/ogl/blob/057a01d7a3f932e17c4c7dc3818fae3517fc0b53/src/extras/Cylinder.js) code and it can easily be modified to pipe. The code is clean and intuitive.

Thanks for the great library!
