### ISSUE TITLE
Video textures broken on mobile browsers

### ISSUE THREAD

**Issue by shampliu** [oframe/ogl#166]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/8483660/217715288-f9f12060-fdca-482d-84d4-bc61cdba623e.png">

**Comment by gordonnl** [comment]
Thanks for letting me know! I can confirm that I also see the issue on iOS. 
I don't have time right at the moment to look into it however. 
I'm guessing it's an issue with the video implementation and not OGL itself - I'm not sure what has changed recently in Webkit regarding videos.
