### ISSUE TITLE
Cannot import `ogl` in SvelteKit when SSR is enabled

### ISSUE THREAD

**Issue by dkrutsko** [oframe/ogl#167]
Hello, we use `ogl` a lot in our SvelteKit project, but we do so with server-side rendering (SSR) enabled. One of the caveats of using SSR is that variables such as `window` and `navigator` are not available during the first pass of the render. As such, your addition in `0.0.114` [here](https://github.com/oframe/ogl/commit/d076b77ad75b5f6b213bd594815805e699c54813#diff-0b508e0f00653696bec59aad24774b2cd5174cef4cc6e4a002971244a6bd5bbdR9) breaks this. `0.0.113` did not have this problem. If possible, I would like to see the `isCreateImageBitmap` function go from being an IIFE to instead being a regular function you call, which caches the result using [`memorizeOne`](https://www.npmjs.com/package/memoize-one) or similar.

**Comment by gordonnl** [comment]
Thanks for bringing that to my attention! That should be fixed now as of `0.0.116`.
