### ISSUE TITLE
Is there a way to convert the hit from Raycast to normalized uv coordinates?

### ISSUE THREAD

**Issue by shampliu** [oframe/ogl#17]
I noticed that the Raycast intersected object has `distance` and a 3D `localPoint` but I want to convert this to UV coordinates. My use case is intersecting the mouse coordinates with textured planes to apply shader effects where the cursor lies on the plane.

**Comment by gordonnl** [comment]
Hey @shampliu, thanks for the request.

Currently there is nothing more complex implemented that would give you this info, just sphere and box hit tests. One day adding geometry ray testing might be a good idea (testing against each triangle in a mesh), however for your use case, I might suggest that there could be other ways of deriving the UV coordinate that would be much simpler and more efficient, as geometry ray testing can get very heavy.

For example if you use the ```localPoint```, and compare it to the center and size of your plane, you could potentially translate it to a ```0 > 1``` range?

In general, I'm hesitant to add really heavy sections to the library.I find you can get away with 95% of use cases with sphere and box hit tests, and in the case of complex 3D apps, I'd still strongly recommend ThreeJS - it's got a huge amount of well-tested modules for things such as this.

Cheers
