### ISSUE TITLE
Semantic Versioning for Major version zero (0.y.z)

### ISSUE THREAD

**Issue by pschroen** [oframe/ogl#175]
A proposal for moving to the same semantic versioning as three.js, this has been a hot topic over the years, however the three.js maintainers are sticking with the [Major version zero (0.y.z)](https://semver.org/#spec-item-4) convention as it's specifically meant for development with potentially breaking changes of each release.

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

I should also point-out the core features and functionality haven't really changed much with OGL, compared to three.js which (especially this year) really does have breaking changes with each release. 😅

All of this to say, maybe it's time to remove the alpha note in the readme, imho this library is very stable in comparison, and warrants removing the notice and switching to at-least "Major version zero (0.y.z)", with breaking changes inferred. 😉

Let me know what you think!

References:
 - https://semver.org/#spec-item-4

**Comment by gordonnl** [comment]
Sure, let's do 1.0.0! Thanks for the input and reference.
