### ISSUE TITLE
MipMaps get disabled on non-POT even on WebGL2

### ISSUE THREAD

**Issue by coomdev** [oframe/ogl#179]
https://github.com/oframe/ogl/blob/8d86f500d04c3e7a16217e20e17fcb2650cf3522/src/extras/TextureLoader.js#L157

Happens when using the .load method, other paths do properly check for WebGL2, except this one, so mipmaps get disabled even though they're supported.

**Comment by gordonnl** [comment]
Thanks for finding that!

**Comment by coomdev** [comment]
Also, [two lines below](https://github.com/oframe/ogl/blob/8d86f500d04c3e7a16217e20e17fcb2650cf3522/src/extras/TextureLoader.js#L159), you're only changing the image filter if it's set to `NEAREST_MIPMAP_LINEAR`, but `NEAREST_MIPMAP_NEAREST`, `LINEAR_MIPMAP_NEAREST` and `LINEAR_MIPMAP_LINEAR` also are values that are valid in WebGL1. Since the filter is not reset for these, this would causes rendering issues when using NPOT textures in WebGL1 contexts.
