### ISSUE TITLE
Alternative to Three.js's onBeforeCompile function?

### ISSUE THREAD

**Issue by monolithMktg** [oframe/ogl#187]
Not exactly an issue, but I seek some help.

I want to use `onBeforeCompile `'s alternative for mimicking this tutorial: [https://tympanus.net/codrops/2019/11/13/high-speed-light-trails-in-three-js/](url)

**Comment by repalash** [comment]
There are no materials in ogl like in three.js. A Program can be created with any shader source you like and used as a material

**Comment by monolithMktg** [comment]
Thank you very much. Makes sense.
