### ISSUE TITLE
GLTF load error

### ISSUE THREAD

**Issue by monolithMktg** [oframe/ogl#191]
I am importing a glb file in OGL, which usually works, only this time I am getting this error in the log:
![capture_240](https://github.com/oframe/ogl/assets/94358787/d249ba02-ea8b-4cb4-b5d0-3e3456d66509)

This is the glb file:
https://easyupload.io/ludf72

Any help would be greatly appreciated.

**Comment by gordonnl** [comment]
Is the file using Draco compression? That's not currently supported

**Comment by monolithMktg** [comment]
> Is the file using Draco compression? That's not currently supported

Oh that was the problem. I didn't check the "Compression" option in Blender export and it seems to have fixed it. Thank you very much Nathan for the prompt response and for this beautiful library. :D
