### ISSUE TITLE
Transparent textures?

### ISSUE THREAD

**Issue by jesperlandberg** [oframe/ogl#20]
Thanks for a great little framework.

I'm having problems getting transparent textures to work. I have tried these:

`transparent: true` on program
`premultiplyAlpha: true` on texture
`premultipliedAlpha: true` on the renderer.

Also tried these in the shader:

`gl_FragColor = vec4(color.rgb * color.a, color.a);`

And:

```
if (color.a < .5) {
  discard;
}
```

But can't seem to get it to work. Any tip?

**Comment by gordonnl** [comment]
For transparent blending, you definitely need ```transparent: true``` on the program, however the other parameters aren't required. 

I would pass in time as a uniform, and set it to the alpha value to test, making sure the issue isn't related to something else. eg:
```gl_FragColor.a = sin(uTime) * 0.5 + 0.5;```

Discarding is different to transparent blending, as it either draws or doesn't. It's usually called alpha clipping or alpha masking. I use it in conjunction with transparency sometimes to reduce overdraw and z-depth issues (like in the Sort Transparency example). There are no parameters needed to get ```discard``` working, so if that doesn't work either, the issue might be with the value you're querying in the condition.
