### ISSUE TITLE
HTMLCanvasElement missing from ImageRepresentation

### ISSUE THREAD

**Issue by hansagames** [oframe/ogl#210]
Hi,

I think we should add `HTMLCanvasElement[]` and `HTMLCanvasElement` to `ImageRepresentation` as possible types.

```
export type ImageRepresentation =
    | HTMLImageElement
    | HTMLVideoElement
    | HTMLImageElement[]
    | ArrayBufferView
    | CompressedImage;
```

**Comment by pschroen** [comment]
`HTMLCanvasElement` was just added in #198 though I'll also add `HTMLCanvasElement[]`, assuming that should work.
