### ISSUE TITLE
Source code in ts

### ISSUE THREAD

**Issue by matiasngf** [oframe/ogl#213]
Hi!
I noticed that the code is in JS and that there are hand-written declaration files.
I was thinking in building a PR with a typescript version. I could try to do it in a way that allows for a smooth transition.
Does it make sense?

**Comment by pschroen** [comment]
Hi Matias,

There was already a [TypeScript version](https://github.com/nshen/ogl-typescript) by @nshen a few years ago, and the declaration files are a combination of hand-written and automatically generated by @CodyJasonBennett and myself.

@gordonnl can chime in here as well, though currently there is no interest in transitioning the library to TypeScript. We're taking a similar approach as three.js where the library itself is vanilla JavaScript, that can run natively in the browser without any compiling or bundling needed.

Here's the previous TypeScript discussions and PR for reference:
- #24
- #135
- #188

**Comment by matiasngf** [comment]
Hi! make sense, thanks for the reply!
