### ISSUE TITLE
Error when updating vec3 uniforms

### ISSUE THREAD

**Issue by TheoGil** [oframe/ogl#22]
Hello!

I'm getting the following error when trying to update a vec3 uniform:
```
setValue.set is not a function
```
I tried both those solutions to update the uniform's value and they both yield that same error
```js
// First try, won't work
this.program.uniforms.uColor1.value = ogl.Color.hexToRGB(hex);

// Second try, won't work either
const color = ogl.Color.hexToRGB(hex);
this.program.uniforms.uColor1.value[0] = color[0];
this.program.uniforms.uColor1.value[1] = color[1];
this.program.uniforms.uColor1.value[2] = color[2];
```

This error is happening at this particular line: https://github.com/oframe/ogl/blob/master/src/core/Program.js#L224

Updating float type uniforms does not yield any error.

Is this a bug or I am missing something an this isn't the right way to update vec3 type uniforms?

Thanks!

**Comment by gordonnl** [comment]
Hey @TheoGil,
When using any Math classes, please use the ```new``` keyword. eg.
```
this.program.uniforms.uColor1.value = new ogl.Color(hex);
```
Or if you're just trying to update an existing color's value:
```
this.program.uniforms.uColor1.value.set(hex);
```
I will look into making some changes to avoid this error however, thanks for your post!

**Comment by TheoGil** [comment]
Ok I got it now.

My issue was that I initialized my uniforms without using the Vec3 class at all... 🤦‍♂ 
I guess I got mixed up and thought `ogl.Color.hexToRGB` returned a new instance of Color 🤷‍♂ 

Instead of 
```js
new ogl.Program(.gl, {
  vertex,
  fragment,
    uniforms: {
        uTime: { value: 0 },
        uColor1: { value: ogl.Color.hexToRGB(hex) },
    }
})
```

I should use
```js
new ogl.Program(.gl, {
  vertex,
  fragment,
    uniforms: {
        uTime: { value: 0 },
        uColor1: { value: new ogl.Color(hex) },
    }
})
```

Thanks for your help @gordonnl

**Comment by gordonnl** [comment]
I've updated OGL in two places to help avoid this type of issue:
 - added support for regular array uniform caching, so the ```setValue.set``` error shouldn't occur
 - moved the ```hexToRGB``` function to a new ```ColorFunc``` class to avoid confusion
