### ISSUE TITLE
GLTF Alpha blend material issues

### ISSUE THREAD

**Issue by monolithMktg** [oframe/ogl#222]
I am exporting a simple bottle glb model from **Blender** where there is some transparency applied, through the `Alpha` value in material, and `Blend Mode` is set to `Alpha Blend`.

Viewing the gltf in OGL's gltf example and Three's ( [GLTF Viewer](https://gltf-viewer.donmccurdy.com/) ) shows a big difference. OGL displays some artifacts on the model whereas Three JS shows the model's transparency correctly. Is this a bug with OGL?

The images for both the viewers as well as the Blender file is attached with this issue. Hopefully, someone will help.

GLB File: https://easyupload.io/3afe54

![capture_366](https://github.com/oframe/ogl/assets/94358787/76689ecd-ac31-4d8c-b795-5862f1a98937)
![eXkFwE4jnJ](https://github.com/oframe/ogl/assets/94358787/0cf33a93-47e2-49c2-9f6a-b9e79994bef2)

**Comment by monolithMktg** [comment]
Another example of weird gltf with alpha artifacts. This time, the default Blender cylinder. Works perfectly in Thee JS. What could be the issue?
![capture_368](https://github.com/oframe/ogl/assets/94358787/acb7a32c-2f8e-46d7-8ae5-b2746cfde7a2)

**Comment by monolithMktg** [comment]
I could really use some help here. Is there something wrong or needs to be adjusted in the blendFunc?

With the program's `transparent` value set to `gltf.alphaMode === 'BLEND'`, this is the `blendFunc` value:
`Object { src: 1, dst: 771, srcAlpha: undefined, dstAlpha: undefined }`

Does something needs to be manually set for `srcAlpha` and `dstAlpha`?

**Comment by gordonnl** [comment]
If you add `depthWrite: false` to the Program definition, it will appear as per the threejs example

**Comment by monolithMktg** [comment]
> If you add `depthWrite: false` to the Program definition, it will appear as per the threejs example

Thank you very much for the fix, @gordonnl . It did work in the case of bottle.

But not when I tried with a simple cylinder, exported from Blender, with some transparency. Here is the glb file: [link](https://easyupload.io/qph26h).

Thanks again for the patience and for this wonderful library. :D

![capture_369](https://github.com/oframe/ogl/assets/94358787/31941014-a33c-4b97-8f57-3a40e09fd07b)
![capture_372](https://github.com/oframe/ogl/assets/94358787/374439b4-82dd-4479-a42b-524b1e68a89f)

**Comment by monolithMktg** [comment]
> If you add `depthWrite: false` to the Program definition, it will appear as per the threejs example

Thank you so much @gordonnl !

Would love to see the greyed out examples also completed so I can learn new things in Webgl through OGL. :D
