### ISSUE TITLE
Texture `.width` and `.height` are undefined after texture load

### ISSUE THREAD

**Issue by davcri** [oframe/ogl#225]
I'm loading textures using TextureLoader like the example below, however I .width and .height are undefined after the texture load.

Is this expected?

```js
        const texture = TextureLoader.load(gl, {
          src: "https://picsum.photos/id/277/512/512.jpg",
        });

        texture.loaded.then(() => {
          console.log(texture.width, texture.height); // "undefined undefined"

          setTimeout(() => {
            console.log("After 1s: ", texture.width, texture.height); // "512 512"
          }, 1000);
        });
```

MRE: https://codesandbox.io/p/sandbox/fervent-hawking-99kpl2

**Comment by gordonnl** [comment]
Currently the texture width/height is stored upon first `update` after an image source is updated.
If you need the width/height as soon as it's loaded, you can use `texture.image.width` or call `texture.update()` first

**Comment by davcri** [comment]
Thank you @gordonnl for the quick reply. Calling `.update()` did the trick.
