### ISSUE TITLE
Simple gl.TEXTURE_2D_ARRAY problem

### ISSUE THREAD

**Issue by monolithMktg** [oframe/ogl#240]
**FIXED**:
Thanks to @eXponenta , I figured I had a problem with my async/await code for loading the image. I really wish this amazing repo had a "**Discussions**" tab as I don't feel wise to ask such questions under "**Issues**".

I have a tiled image, 960px (w) x 1620px (h), with each block being 540px high, that I want to sample with `sampler2DArray`. I believe I am doing everything correctly but no texture is displayed.

 **Frag shader:**
```
uniform highp sampler2DArray uTex;

varying vec2 vUv;
varying vec3 vNormal;

void main() {
    vec2 uv = vUv;
    vec3 color = texture( uTex, vec3( uv, 0. ) ).rgb;    
    gl_FragColor = vec4( color, 1.);
}
```

**And this is how I am loading the image:**
```
this.geometry = new Plane(this.gl);

    let vertPrefix = this.renderer.isWebgl2
    ? /* glsl */ `#version 300 es
      #define attribute in
      #define varying out
      #define texture2D texture`
    : ``;

    let fragPrefix = this.renderer.isWebgl2
    ? /* glsl */ `#version 300 es
      precision highp float;      
      #define varying in
      #define texture2D texture
      #define gl_FragColor FragColor
      out vec4 FragColor;
    `
    : `
      #extension GL_OES_standard_derivatives : enable
      precision highp float;
    `;


this.tex = new Texture( this.gl, {
      target: this.gl.TEXTURE_2D_ARRAY,
      length: 3,
      width: 960,
      height: 540,
    });
    
    let image = new Image();
    image.src = './src/images/anim2.jpg';
    image.onload = () => {
      this.tex.image = img;      
      this.tex.needsUpdate = true;      
    };

    this.tex.update(); 

    this.program = new Program(this.gl, {
        vertex: vertPrefix + defines + vert,
        fragment: fragPrefix + defines + frag,
        uniforms: {
            uTime: { value: this.speed },
            uResolution: { value: new Vec2( this.gl.canvas.width, this.gl.canvas.height ) },
            uTex: { value: this.tex }
        },
    });
```

I also tried with the new **Texture3D** class but to no avail.

This is the image:
![anim2](https://github.com/user-attachments/assets/dd35f77c-f841-479a-941e-5d48c74ec793)

**Comment by monolithMktg** [comment]
UPDATE:
Tried this with Texture3D, no warnings or errors, but still texture doesn't show up:

```
    this.tex = new Texture3D( this.gl, {
      src: './src/images/anim2.jpg',
      length: 3,
      width: 960,
      height: 540,
    } );
```

**Comment by eXponenta** [comment]
Yo should load via buffer only. Webgl not support image as slices. 

```
    // load source
    const imageSource = await (await fetch('./src/images/anim2.jpg' )).blob()
    const refImage = await createImageBitmap(  imageSource, { imageOrientation: "flipY" } );
    
    const canvas = document.createElement('canvas');
    canvas.width = refImage.width;
    canvas.height = refImage.height;
    const ctx = canvas.getContext('2d');

    ctx.drawImage( refImage, 0, 0 );
    /// unroll to imageData
    const imageData = ctx.getImageData(0, 0, refImage.width, refImage.height );

    this.tex = new Texture( this.gl, {
      target: this.gl.TEXTURE_2D_ARRAY,
      // load raw bytes
      image: imageData.data,
      length: 3,
      width: 960,
      height: 540,
    } );
    
    
    ```

**Comment by monolithMktg** [comment]
@eXponenta Thank you so much for your reply. But it still doesn't work. Unable to use external image link on jsfiddle/codepen hence I am attaching the project file here:
[texture array - Copy.zip](https://github.com/user-attachments/files/17686159/texture.array.-.Copy.zip)

I have commented out the **3 approaches** that I am trying:
**1. With the stock OGL's Texture class,
2. Your approach
3. With OGL's Texture3D class which also does the imageData reading like your example**

![Code_T8PKXrYqlJ](https://github.com/user-attachments/assets/acb50f31-dcf4-4fc1-acc7-ef2bf5cf6642)


`Yo should load via buffer only. Webgl not support image as slices.` but following [this WEBGl2 Texture Arrays tutorial ](https://youtu.be/FCkMPkgWClo?si=vMDrQzmeVznvqPxW), during the simplest example at around the 5:25 mark, just the image url works. Infact, throughout the whole video, just loading the image and sending it to shader via `this.gl.texImage3D` is all that is needed.

Also, since the height of `anim1.jpg` texture is **2048px**,  I believe we need to pass height/length to the `Texture `that is **1024px**. In this [**WEBGL2** Samples repo ](https://github.com/WebGLSamples/WebGL2Samples/blob/master/samples/texture_2d_array.html) too,  nothing special is done for `TEXTURE_2D_ARRAY`.

I am really clueless what is going wrong?

I only get a black screen and the texture doesn't show up.
