### ISSUE TITLE
Boilerplate code for shaders

### ISSUE THREAD

**Issue by munrocket** [oframe/ogl#26]
Did you ever consider some shader API for skinning? Like glslify but for web maybe?

**Comment by gordonnl** [comment]
Hey mate,

Do you mean to host a range of shader snippets (including skinning) within es6 modules? GLSLify, but not on npm?

Threejs have a [large selection of them](https://github.com/mrdoob/three.js/tree/dev/src/renderers/shaders/ShaderChunk)!

I feel it's a bit out of the scope of this library's core - it's definitely a good approach for a larger engine though! OGL is for more for devs who like tinkering with simple shaders manually.

I imagine when I get into supporting GLTF, I'll have to work in some epic dynamic shader logic in the extras, but I'm not intending to have re-usable snippets for modular use.

**Comment by munrocket** [comment]
I see, looks reasonable.
