### ISSUE TITLE
Controls bug

### ISSUE THREAD

**Issue by Dmitry-Sm** [oframe/ogl#33]
When i set property "position: absolute" to canvas, controls become inactive. 
Example - https://bvdp.ru/share/dsm/temp/ogl-test/
Screenshot - https://monosnap.com/file/RLMBKkkqDsaKD61qghyvb1UESKfoRI

**Comment by gordonnl** [comment]
That seems rather odd!

Could you please make a codesandbox so that I can see your implementation?

Here is a working example using orbit-controls that has the canvas in `position: absolute`
https://oframe.github.io/ogl/examples/?src=orbit-controls.html

**Comment by Dmitry-Sm** [comment]
Just copy "Projection and Raycasting" - https://codesandbox.io/s/ogl-bug-test-g36nj?fontsize=14&hidenavigation=1&theme=dark

**Comment by gordonnl** [comment]
Ok I see the issue now, by default the orbit class using the `document` object to attach its event listeners.
https://github.com/oframe/ogl/blob/4d1d51c21b7c7537e0d8644c420c4c2820328304/src/extras/Orbit.js#L14

So when the canvas is absolute, the document has no content, and therefore 0 height.
There are a couple of quick solutions.

Either give the page some height:
```css
html,
body {
  height: 100%;
}
```

Or pass in the canvas as the element:
```js
const orbit = new Orbit(camera, {element: gl.canvas});
```
