### ISSUE TITLE
Question on Orbit wheel event

### ISSUE THREAD

**Issue by dp50mm** [oframe/ogl#35]
Hi Nathan,

Love the library and working with it! I have a question about the Orbit controls.
I was wondering why is the _wheel_ event directly connected to the window instead of the element provided in the function call when creating an orbit?
[Orbit.js line 313 & 322](https://github.com/oframe/ogl/blob/d74f29987d27a0b29ae6343a35c5c92237ff982d/src/extras/Orbit.js#L313)

In the current implementation it triggers scrolling everywhere in the window even though the canvas might not be the full browser window size. In a local branch I changed it to attach the event listener the same element as the other events and it seems to work as I expected, where it only zooms when scrolling on the canvas and not on the other elements on the page.

**Comment by gordonnl** [comment]
Thanks for that @dp50mm!
I don't recall if there was a reason haha, but it seems to work fine for me.
The Orbit class has been needing some love for quite a while, hopefully I get around to it soon.
