### ISSUE TITLE
Orthographic Camera Zoom?

### ISSUE THREAD

**Issue by MadebyAe** [oframe/ogl#36]
Hello,

Just wondering, Is possible to have the zoom functionality using Orthographic camera as Three.js does. I tried multiple times but I am not able to move the camera.

Thanks!

https://github.com/mrdoob/three.js/blob/e2d4abb9cfe3d1b5c8d2e3ffcbbee637b25ba19a/src/cameras/OrthographicCamera.js#L15

**Comment by gordonnl** [comment]
Yeah sure! I guess that value would just divide the `left, right, etc` values.

To be honest I've never needed to use a dynamic Orthographic camera, what are you using it for? I'm wondering what the ideal API would be, as currently you'd need to pass in `top, right, bottom, left` for every update, which doesn't seem ideal.
