### ISSUE TITLE
Compressed textures not showing on iPad iOS 13

### ISSUE THREAD

**Issue by eXponenta** [oframe/ogl#42]
Nothing showing on compressed texture example. Black screen.
iPad 2018, ios13.3.1.

**Comment by gordonnl** [comment]
Thanks for testing that. I fixed the silly bug here b1a5a70, however for some reason the pvrtc extension is returning `null` for iPad, when it should be supported. So currently it's falling back to jpg.

`gl.getExtension('WEBGL_compressed_texture_pvrtc'); // null`

The extension works with Threejs [here](https://timvanscherpenzeel.github.io/texture-compressor/) however, so there must be some other extension I need to set (or something else I'm missing).

**Comment by gordonnl** [comment]
Fixed in 600f4d7.
Apparently it needed to be prefixed with `WEBKIT_`
