### ISSUE TITLE
group of objects 

### ISSUE THREAD

**Issue by gregja** [oframe/ogl#48]
Hi,
I discovered OGL recently. I like it a lot and I use it for my 3D experiments in that project :
https://github.com/gregja/oglXperiments

Maybe it exists yet in OGL, but I didn't find it in the examples :  is it possible to create groups of objects ? 

The group would be a virtual artefact, not a visible object, but the children of the group would inherit of parameters of the group, like position, scale and rotation. It would be helpful to create joints with specific rotation, applied to the children of the joint. I have an example with this sketch (inspired of an old processing sketch), where I would like to hide the cubes I used to attach the wings to the book : 
http://ledefrichoir.com/labo/oglXperiments/ogl_flying_book.html

Thank's a lot for your attention,
Best regards

**Comment by akira-cn** [comment]
Maybe use Transform as group?

```js
            leftJoint = new Transform(gl);
            rightJoint = new Transform(gl);
            if (idx == 0) {
                leftJoint.addChild(childLvl1);
            } else {
                rightJoint.addChild(childLvl1);
            }
```

**Comment by gordonnl** [comment]
Hey Gregory,
Your flying book is looking great already!

Thanks @akira-cn for your response, which is indeed correct: `Transform` is a null scene object that holds unique transform data (position, rotation, scale), so it is the equivalent for a Group in other libraries/applications. The `Mesh` class extends `Transform`, so it also contains all of the same functionality. 

The [Scene Graph Hierarchy](https://oframe.github.io/ogl/examples/?src=scene-graph.html) example touches on it somewhat, however you can either use `addChild()` as @akira-cn demonstrated, or `setParent()`, which works in the opposite direction - eg `child.setParent(parent)`.

**Comment by gregja** [comment]
Thank's to @gordonnl and to @akira-cn  for the tip.
I renamed my script in "flying box" instead of "flying book", you'll understand why when you'll see it ;)
http://ledefrichoir.com/labo/oglXperiments/ogl_flying_box.html
