### ISSUE TITLE
bug on Transform

### ISSUE THREAD

**Issue by gregja** [oframe/ogl#50]
Hello,
I come back with my "flying box" (previously "flying book") because I met a bug with the Transform class. 
I followed the proposition of @akira-cn to replace "new Box" by "new Transform", but the script crashes with this message : 
TypeError: node.geometry.attributes is undefined  (in Camera.js)

Maybe I made something wrong. 
You can see the bug in live mode by using the option "jointDefault" with the value "Not visible" on this page : 
http://ledefrichoir.com/labo/oglXperiments/ogl_flying_box.html
Thank's for you help.
Best regards
Greg

**Comment by gordonnl** [comment]
This is because you're treating `Transform` as a geometry, which it isn't.

The error is in the lines below:
```
geometry = new Transform(gl);
...
let childLvl1 =  new Mesh(gl, {mode: gl[settings.rendering], geometry, program});
```

Instead, the `Transform` is *replacing* your `Mesh`. So:
```
let childLvl1 = new Transform(gl);
```

**Comment by gregja** [comment]
Ok @gordonnl , if I well understood, you suggest to drop the position and rotation of my joints : 
 
 let childLvl1 =  new Mesh(gl, {mode: gl[settings.rendering], geometry, program});
 // childLvl1.position.set(level1.position[0], level1.position[1], level1.position[2]);
 // childLvl1.rotation.set(level1.rotation[0], level1.rotation[1], level1.rotation[2]);
 book.addChild(childLvl1);

So I can't replace Box by Transform, because I need to apply some position and rotation to my joints. 
If I don't do that, my joints will be positioned on the center of the main cube (which is not what I want). 
So I think a Group class, with position and rotation attributes, would be very helpful for different types of complex shapes, specially shapes with articulations.
It's not hurry for me, but if you could do that in a future version, it would be really cool.
Thank's.

**Comment by gordonnl** [comment]
> if I well understood, you suggest to drop the position and rotation of my joints

No, that's not what I was saying - I was saying to replace your `Mesh` with `Transform`.
```
let childLvl1 = new Transform(gl); // Not Mesh
book.addChild(childLvl1);
```

> So I think a Group class, with position and rotation attributes, would be very helpful for different types of complex shapes, specially shapes with articulations.

That is what the `Transform` class is used for.

**Comment by gregja** [comment]
Ok, sorry for my mistake. Now it works fine, you can see the result on line.
Best regards,
Greg
