### ISSUE TITLE
Canvas blur issue

### ISSUE THREAD

**Issue by mukeshpanchal27** [oframe/ogl#51]
Using this demo https://oframe.github.io/ogl/examples/?src=mouse-flowmap.html I have created a new example but I face some issues on the frontend.

The front end of the demo shows blurs SVG image in the canvas.

**Javascript Code:**

    import {Geometry} from '../src/core/Geometry.js';
    import {Program} from '../src/core/Program.js';
    import {Renderer} from '../src/core/Renderer.js';
    import {Camera} from '../src/core/Camera.js';
    import {Transform} from '../src/core/Transform.js';
    import {Mesh} from '../src/core/Mesh.js';
    import {Texture} from '../src/core/Texture.js';
    import {RenderTarget} from '../src/core/RenderTarget.js';
    import {Vec2} from '../src/math/Vec2.js';
    import {Vec4} from '../src/math/Vec4.js';
    import {Flowmap} from '../src/extras/Flowmap.js';
    import {Triangle} from '../src/extras/Triangle.js';

        
        const vertex = /* glsl */ `
            attribute vec2 uv;
            attribute vec2 position;

            varying vec2 vUv;

            void main() {
                vUv = uv;
                gl_Position = vec4(position, 0, 1);
            }
        `;

        const fragment = /* glsl */ `
            precision highp float;
                    precision highp int;
                    uniform sampler2D tWater;
                    uniform sampler2D tFlow;
                    uniform float uTime;
                    varying vec2 vUv;
                    uniform vec4 res;

            void main() {

                            // R and G values are velocity in the x and y direction
                            // B value is the velocity length
                            vec3 flow = texture2D(tFlow, vUv).rgb;
              vec2 uv = .5 * gl_FragCoord.xy / res.xy ;

              vec2 myUV = (uv - vec2(0.5))*res.zw + vec2(0.5);
              myUV -= flow.xy * (0.15 * 0.5);
              vec3 tex = texture2D(tWater, myUV).rgb;

              gl_FragColor.rgb = vec3(tex.r, tex.g, tex.b);
              gl_FragColor.a = tex.r;
                    }
        `;

        {
            const renderer = new Renderer({dpr: 2});
            const gl = renderer.gl;
            document.body.appendChild(gl.canvas);

            // Variable inputs to control flowmap
            let aspect = 1;
            const mouse = new Vec2(-1);
            const velocity = new Vec2();

            function resize() {
                renderer.setSize(window.innerWidth, window.innerHeight);
                aspect = window.innerWidth / window.innerHeight;
            }
            window.addEventListener('resize', resize, false);
            resize();

            const flowmap = new Flowmap(gl);

            // Triangle that includes -1 to 1 range for 'position', and 0 to 1 range for 'uv'.
            const geometry = new Triangle(gl);

            const texture = new Texture(gl, {wrapS: gl.REPEAT, wrapT: gl.REPEAT});

            const img = new Image();
            img.onload = () => texture.image = img;
            img.src = 'assets/Alienation-o.svg';

            const program = new Program(gl, {
                vertex,
                fragment,
                uniforms: {
                    uTime: {value: 0},
                    tWater: {value: texture},
                    res: {
                        value: new Vec4(window.innerWidth, window.innerHeight, 1,1)
                      },
                    // Note that the uniform is applied without using an object and value property
                    // This is because the class alternates this texture between two render targets
                    // and updates the value property after each render.
                    tFlow: flowmap.uniform,
                }
            });

            const mesh = new Mesh(gl, {geometry, program});

            // Create handlers to get mouse position and velocity
            const isTouchCapable = 'ontouchstart' in window;
            if (isTouchCapable) {
                window.addEventListener('touchstart', updateMouse, false);
                window.addEventListener('touchmove', updateMouse, false);
            } else {
                window.addEventListener('mousemove', updateMouse, false);
            }

            let lastTime;
            const lastMouse = new Vec2();
            function updateMouse(e) {
                if (e.changedTouches && e.changedTouches.length) {
                    e.x = e.changedTouches[0].pageX;
                    e.y = e.changedTouches[0].pageY;
                }
                if (e.x === undefined) {
                    e.x = e.pageX;
                    e.y = e.pageY;
                }

                // Get mouse value in 0 to 1 range, with y flipped
                mouse.set(
                    e.x / gl.renderer.width,
                    1.0 - e.y / gl.renderer.height
                );

                // Calculate velocity
                if (!lastTime) {
                    
                    // First frame
                    lastTime = performance.now();
                    lastMouse.set(e.x, e.y);
                }
                
                const deltaX = e.x - lastMouse.x;
                const deltaY = e.y - lastMouse.y;
                
                lastMouse.set(e.x, e.y);
                
                let time = performance.now();
                
                // Avoid dividing by 0
                let delta = Math.max(14, time - lastTime);
                lastTime = time;

                velocity.x = deltaX / delta;
                velocity.y = deltaY / delta;

                // Flag update to prevent hanging velocity values when not moving
                velocity.needsUpdate = true;
            }

            requestAnimationFrame(update);
            function update(t) {
                requestAnimationFrame(update);

                // Reset velocity when mouse not moving
                if (!velocity.needsUpdate) {
                    mouse.set(-1);
                    velocity.set(0);
                }
                velocity.needsUpdate = false;

                // Update flowmap inputs
                flowmap.aspect = aspect;
                flowmap.mouse.copy(mouse);

                // Ease velocity input, slower when fading out
                flowmap.velocity.lerp(velocity, velocity.len ? 0.5 : 0.1);

                flowmap.update();

                program.uniforms.uTime.value = t * 0.001;

                renderer.render({scene: mesh});
            }
        }

Check the attached screenshot for more information.

![Mouse Flowmap](https://user-images.githubusercontent.com/10103365/75244296-906cb680-57f1-11ea-9522-445d7fc3e02d.png)

**Comment by mukeshpanchal27** [comment]
@gordonnl can you please help me to resolve the blur issue?

**Comment by gordonnl** [comment]
This isn't an issue with OGL. Nor do you need to tag me directly - I receive notifications already.

Your issue looks to be around incorrect ratio information.
vec2 uv = .5 * gl_FragCoord.xy / res.xy ;
vec2 myUV = (uv - vec2(0.5))*res.zw + vec2(0.5);

res: {
    value: new Vec4(window.innerWidth, window.innerHeight, 1,1)
},

**Comment by mukeshpanchal27** [comment]
Is there any way we can fix this ratio issue or it is not possible to change it from our end

**Comment by gordonnl** [comment]
Unfortunately I don't have time right now to walk you through it. Texture UVing is a fundamental skill and it will help you a lot to get to grips with it.

I would begin by using this [basic full screen shader example](https://github.com/oframe/ogl/blob/master/examples/triangle-screen-shader.html) and adapt it by rendering your texture full screen. 

Then, try resizing your browser, and notice how it affects your image.

Finally, try and edit the `uv` values so that your image does not stretch in any window size.

**Comment by mukeshpanchal27** [comment]
Thanks for the help.

I will check it and try to resolve it. I'm Newby for shader examples any help when you available then it is a big help

Thanks

**Comment by mukeshpanchal27** [comment]
> This isn't an issue with OGL. Nor do you need to tag me directly - I receive notifications already.
> 
> Your issue looks to be around incorrect ratio information. You need to make your image ratio match the canvas ratio.
> 
> I'd look closer into these two areas:
> 
> ```
> vec2 uv = .5 * gl_FragCoord.xy / res.xy ;
> vec2 myUV = (uv - vec2(0.5))*res.zw + vec2(0.5);
> ```
> 
> ```
> res: {
>     value: new Vec4(window.innerWidth, window.innerHeight, 1,1)
> },
> ```
> 
> You also never update these values on resize.
> 
> Good luck!

I have checked this and try to change **rev** but when I change anything on it it will either stop working or change the frontend effect.

**Comment by gordonnl** [comment]
Sorry mate, may I suggest you create a jsfiddle, codesandbox or codepen? That way people can show you what to do, rather than try and explain.
