### ISSUE TITLE
Cached textures bound to gl context that are invalid for different scenes

### ISSUE THREAD

**Issue by subblue** [oframe/ogl#59]
I've hit against an edge case where I am loading different scenes into my app, which sometimes use the same textures. 
When loading the second scene it will pull the texture object [from the cache](https://github.com/oframe/ogl/blob/master/src/extras/TextureLoader.js#L78) but this is invalid as it was created for the `gl` context of the first scene.

As far as I can tell the `gl` context doesn't have a unique identifier that could be included in the [cacheID](https://github.com/oframe/ogl/blob/master/src/extras/TextureLoader.js#L63)

Ideally in my case I would use a `TextureLoader.clearCache()` method to manually reset the cache before loading a new scene to my app.
Happy to create a PR for it.

**Comment by gordonnl** [comment]
Great suggestions!
I've applied both of them in commit ca25b38 (forgot to tag this issue in the message).
Cheers
