### ISSUE TITLE
please add a simple example about light

### ISSUE THREAD

**Issue by ejamshidiasl** [oframe/ogl#64]
Hello
please add some examples about light

OGL is realy good

**Comment by gordonnl** [comment]
Hey Esmail, thanks a lot.

There's actually no such component as a light in OGL, the specific rendering would be handled in the geometry shaders themselves, eg https://oframe.github.io/ogl/examples/?src=pbr.html

And for the shadows that a light would create, they are handled separately, eg https://oframe.github.io/ogl/examples/?src=shadow-maps.html

Hope that helps!

**Comment by ejamshidiasl** [comment]
Ok so i am going to add simple light system and will share it to you.
