### ISSUE TITLE
Any chance to get IE11 support back ?

### ISSUE THREAD

**Issue by Hersir88** [oframe/ogl#66]
Hi,
didn't found better place so will ask it here :)

Right now ogl code don't work on IE11 as some code can not be launched there, I think extend Array was one of it.

Is there plan to get back IE11 or it will be left out ?

Thank you

**Comment by gordonnl** [comment]
Hey!

So I use a lot of es6 features, meaning the code will not work there directly. You will need to transpile the code back to es5 using [babel](https://babeljs.io/) or similar.

On top of this, you will also need to add [this polyfill](https://github.com/greggman/oes-vertex-array-object-polyfill/blob/master/OESVertexArrayObject-polyfill.js) for vertex array objects.

Also be sure to not use any WebGL2 features without any fallbacks (check `renderer.isWebgl2`).

I've supported ie11 a few times with the above steps.
Good luck!
