### ISSUE TITLE
difficulties to use OGL and Oimo together

### ISSUE THREAD

**Issue by gregja** [oframe/ogl#71]
Hi,
I need some help. 
I would like to know if anyone has used OGL and Oimo.js together ? 
Because I'm trying to implement, on OGL, a simplified version of this example :

http://lo-th.github.io/Oimo.js/examples/test_basic.html

The original example is written with Three.js. My intermediate version for OGL is visible here : 

http://ledefrichoir.com/labo/oglXperiments/sources/ogl_oimo_basic.html

On my version, you will see the cubes cross the gray support instead of bouncing on it. I suppose I need to adjust the coordinates system to Oimo.js, but my different tests failed. 

If someone has a trick to offer me, he will receive my eternal gratitude :).
Thank's

**Comment by gregja** [comment]
Hi,
Finally, I found my mistake. It was not where I was searching (as usual :).
I discovered that I placed the "world.clean()" function in the wrong place, loosing the benefit of the creation of the grounds. So finally, it works fine. 
http://ledefrichoir.com/labo/oglXperiments/sources/ogl_oimo_basic.html
I continue to explore the possibilities to mix OGL and Oimo together. For my experiences, I take a lot of inspiration in that repo : 
https://github.com/cx20/jsdo.it-archives
... which contains a lot of examples interesting to adapt to OGL.
Best regards

**Comment by gordonnl** [comment]
Really nice mate!
Sorry I didn't get a chance to help, glad you found your solution.

I just had a super quick look, and I just wanted to correct one line: 
```
let rot = item.oimo.getQuaternion();
item.mesh.rotation.set(rot.x, rot.y, rot.z, rot.w);
```
The `rotation` property on `Mesh` or `Transform` is in Euler coordinates (XYZ), if you want to use quaternions, use the `quaternion` property instead., eg:
```
let quat = item.oimo.getQuaternion();
item.mesh.quaternion.copy(quat);
```

**Comment by gregja** [comment]
Hi @gordonnl,
Thank's a lot for you advice. 
I've tested it on my local server, but it doesn't work. 
The balls completely disappeared. Are you sure that the "quaternion.copy" function works fine ?

**Comment by gordonnl** [comment]
Ah yeah ok, Oimo (like Threejs) uses object notation (x/y/z) https://github.com/lo-th/Oimo.js/blob/gh-pages/src/math/Vec3.js#L3

Whereas OGL Math classes use arrays (meant to be more efficient). So you're right, in this case, you'd need to use `set`.

**Comment by gregja** [comment]
Oh yes, now it works. I paste here the good syntax for other devs : 
 
 let quat = item.oimo.getQuaternion();
 item.mesh.quaternion.set(quat.x, quat.y, quat.z, quat.w);

... and I understand now why I had some weird rotations in my other examples. So I have some fixes to do. 
Thank's a lot @gordonnl 👍
