### ISSUE TITLE
use OpenJSCad with OGL

### ISSUE THREAD

**Issue by gregja** [oframe/ogl#72]
Hi @gordonnl ,
I hope everyhing is OK for you (reference to coronavirus).
This is not an issue, just an information.
I made some experiments to use OpenJSCad (for modelization) with OGL (for rendering). 
You can test it with that 2 options : 
- a fix shape :
http://ledefrichoir.com/labo/oglXperiments/sources/ogl_csg1.html
- shape editable : 
http://ledefrichoir.com/labo/oglXperiments/sources/ogl_csg2.html

It's not perfect, because some shapes with extrusions are badly rendered, for the moment.
To improve the rendering on extrusions, I suppose I should take example on that ThreeJS wrapper : 
https://joostn.github.io/OpenJsCad/src/threecsg.js
... but I'm not a specialist of WebGL (and of ThreeJS), so, probably it will take a long time :( 

Take care,
Greg

PS : all source code of my experiments is here https://github.com/gregja/oglXperiments

**Comment by gregja** [comment]
Hi,
It's again me ;) 
Today, I added a new option which is a gear generator, largely inspired by this tutorial : 
https://joostn.github.io/OpenJsCad/

the link to my version coded with OGL : 
http://ledefrichoir.com/labo/oglXperiments/sources/ogl_csg3.html

In my version of the gear generator, I obtained an interesting rendering by using the TRIANGLE_FAN mode. It is not a perfect rendering but it's not too bad (much better than TRIANGLES and TRIANGLE_STRIP). I'll try to improve the rendering later.

I added a button to export the shape in a STL file (for 3D printer). It's possible to import the STL file in Tinkercad (for example) to view it.
Bye

**Comment by gordonnl** [comment]
Hey mate,
This is really awesome! Making a link to CAD, and especially export to STL is a great idea.
I'm gonna close this issue, but feel free to keep posting updates!
Cheers

**Comment by gregja** [comment]
Hello Nathan,
I fixed the bug on the rendering of the gear generator. The rendering is good now.
I applied the same fix on those 3 examples (be careful to refresh the cache of the browser if you saw the previous versions) : 

http://ledefrichoir.com/labo/oglXperiments/sources/ogl_csg1.html
http://ledefrichoir.com/labo/oglXperiments/sources/ogl_csg2.html
http://ledefrichoir.com/labo/oglXperiments/sources/ogl_csg3.html

So now, it' time to modelize ;)
Cheers
