### ISSUE TITLE
Add VR support - exposing x and y for setViewport

### ISSUE THREAD

**Issue by hansagames** [oframe/ogl#77]
Hi,
in order to render in specific viewport position x,y position needs to be exposed from ogl api, right now it have default 0,0.

This feature is necessary for VR rendering as each eye needs specific position

**Comment by gordonnl** [comment]
You're correct in that this isn't supported. I think for VR, an extra class that replaces the render method would be a better approach. This would be a great addition to OGL! I haven't touched VR in a few years, so haven't needed the functionality, personally.

You should also feel free to use gl calls directly, when doing rare, advanced techniques, and basically replace the functionality in the `Renderer.render` method (eg calling `mesh.draw({ camera })`.

All that said, I'm not against adding `x` and `x` properties to the `Renderer.render` function - do you have a use case in mind, other than for VR?

**Comment by Hersir88** [comment]
I dont know any other use cases really, just for VR
