### ISSUE TITLE
Set custom frame buffer before render

### ISSUE THREAD

**Issue by Hersir88** [oframe/ogl#78]
Hi,
I need to pass custom frame buffer for rendering, so tried to use `bindFramebuffer` on renderer, but this dont work as on each render `bindFramebuffer` is called without any params so it sets it to null, 

what would be the best way to expose such functionality ?

**Comment by gordonnl** [comment]
To render to a `RenderTarget`, pass it in as a `target` as per [this example](https://github.com/oframe/ogl/blob/master/examples/render-to-texture.html#L135).

You can check out the working example here - https://oframe.github.io/ogl/examples/?src=render-to-texture.html

As a general rule of thumb, the examples are there as reference, so take a look to see if there's anything similar to what you're trying to achieve.
