### ISSUE TITLE
Consolidate options for geometry primitives?

### ISSUE THREAD

**Issue by nikrowell** [oframe/ogl#8]
More of an idea than an issue, and obviously an API breaking change, but would it make sense to consolidate the constructor args for primitives (Sphere, Cube, Plane) into a single options object to allow an optional third `attributes` object to be passed to the parent Geometry class? 

Looks like you can achieve the same result by calling `addAttribute` on an instance, but this at least makes the api more concise and consistent. Thoughts?

```js
const plane = new Plane(gl, {width: 5}, {
  color: {
    size: 3,
    data: new Float32Array(...)
  },
});
```

**Comment by gordonnl** [comment]
Although, makes it much more verbose to create a geometry.
eg.
```javascript
const plane = new Plane(gl, 10, 20, 1, 2);
```
vs
```javascript
const plane = new Plane(gl, {width: 10, height: 20, widthSegments: 1, heightSegments: 2);
```
But at the same time, it's more clear, and more similar to the rest of the framework...

**Comment by nikrowell** [comment]
Good point, I suppose the individual args could come after attributes, but I think the primitive width, height etc values would be more commonly used, so you'd often be passing null an empty object as the second arg. Or the constructor could check if the second param is an object, and assume it's the 3-arg version, but that's starting to feel a little hacky.

**Comment by gordonnl** [comment]
I went with the more verbose option, as it matched the rest of the framework and was more clear.
For your example, you could achieve it like:
```javascript
const plane = new Plane(gl, {
    width: 5,
    attributes: {
        color: {size: 3, data: new Float32Array(...)},
    },
});
```
