### ISSUE TITLE
How to pass array of structs to glsl ? 

### ISSUE THREAD

**Issue by hansagames** [oframe/ogl#81]
Hi,
saw in code that there is case for passing array of structs to shader,
but could not find any example how to define such uniforms.

Missing something or its not documented yet ? :)

**Comment by FarazzShaikh** [comment]
Hi @hansagames, what do you mean by an "array of structs". Uniforms can only be of certain types as shown [here](https://webglfundamentals.org/webgl/lessons/webgl-shaders-and-glsl.html#uniforms)

**Comment by hansagames** [comment]
Hi @FarazzShaikh [Program.js](https://github.com/oframe/ogl/blob/master/src/core/Program.js) have this

```
if (split.length === 3) {
                uniform.isStructArray = true;
                uniform.structIndex = Number(split[1]);
                uniform.structProperty = split[2];
}
```

it allows to pass for example such type to shader `Array<{ color: Vec3, direction: Vec3 }>`
and in shader then you have `uniform STRUCT_TYPE someStruct[COUNT];`

I managed to pass ti using ogl but I needed to modify code a bit for uniform handling inside Program.js, so was wondering if it was ever used somewhere

**Comment by gordonnl** [comment]
Hey, thanks for the catch! You're right that it's not documented anywhere (mainly because I don't use them very often) - we should definitely add them to an example somewhere where it would be appropriate.

Please find below an example of how to structure the uniforms when using structs.

GLSL declaration:

```glsl
struct Data {
    vec3 position;
    vec3 direction;
};
uniform Data data;
```

JS uniform definition:

```js
uniforms: {
    data: {
        position: { value: new Vec3() },
        direction: { value: new Vec3() },
    },
}
```

**Comment by hansagames** [comment]
@gordonnl any example on passing array of structs not just one struct ? sorry for writing in closed issue

**Comment by hansagames** [comment]
ok looks like to works the same sorry for distrubution
