### ISSUE TITLE
About Adding OBJLoader

### ISSUE THREAD

**Issue by FarazzShaikh** [oframe/ogl#82]
HI, great library, really useful. I was wondering if you are accepting PRs. I could quickly port over this [OBJLoader](https://github.com/WesUnwin/obj-file-parser) to provide the same functionality but preserving the "no dependency" nature of this project.

**Comment by gordonnl** [comment]
Hey, sorry for the lengthy delay.

Absolutely, that'd be awesome if you could add that as an extra! I personally use JSON or GLTF, so have never looked into it too deeply, however if you think it would be useful to yourself or others, please feel free to make a PR!

Cheers

**Comment by FarazzShaikh** [comment]
Hey! Sure, i will add the OBJLoader in extras along with an example.

**Comment by monolithMktg** [comment]
> 

bhai did you manage to implement OJLoader in OGL? The example is also greyed out.
