### ISSUE TITLE
A question about HDR textures

### ISSUE THREAD

**Issue by Paolo5150** [oframe/ogl#84]
Hey guys,

Quick question, I'm writing my own webgl2 renderer, because why not, I'm at the point where I need to load .hdr images (you know, IBL stuff). Unsure on how to proceed, I was wondering if your library can help with that? Just need to load the image in the correct format so I can then create my own texture and do the usual (binding, sampling and so on)

Cheers! 

Oh, happy new year btw, only a couple of hours left to 2021 here in Australia

**Comment by gordonnl** [comment]
Hey, I've written a tool for converting HDR images for use in a PBR pipeline [here](https://github.com/oframe/ibl-converter) - included in it are importers for `.hdr` and `.exr` formats - you could just use these directly I believe. It also shows how to export as a HDR image using `.png` with an `RGBM` (M is for shared multiplier) format - which is handy as browsers support the PNG format. With that format in mind, [here is an example](https://github.com/oframe/ogl/blob/master/examples/pbr.html#L94) of how to implement that in a shader (note that the multiplier needs to be the same as the value used when generating the image data).

Happy new year to you too!
