### ISSUE TITLE
Postprocessing: Add support for accessing the original texture before passes are applied

### ISSUE THREAD

**Issue by shampliu** [oframe/ogl#89]
This is needed for effects such as bloom when we blend the original FBO and the blurred FBO in the end.

**Comment by gordonnl** [comment]
This sounds like a great addition.

I haven't touched post shaders in quite a while, would you happen to have a working example of a bloom effect with OGL?

**Comment by shampliu** [comment]
@gordonnl Yes I do, but it doesn't use the Post object, do you want me to modify the Post to support it or just share what I have?

**Comment by gordonnl** [comment]
Even just a [Code Sandbox](https://codesandbox.io/) of what you have would be very helpful!

**Comment by shampliu** [comment]
@gordonnl added a PR above! I'm down to help on this if you need, just not sure what direction to go with supporting it in the Post class.
