### ISSUE TITLE
Loading images through TextureLoader doesn't preload it for the DOM

### ISSUE THREAD

**Issue by shampliu** [oframe/ogl#90]
On my single page app's homepage, I load a couple of images via the TextureLoader to fill some Plane objects in the gl scene. However, when I navigate to another page that uses those same exact image URLs for DOM elements (`img` tags, etc.) I see redundant network request for those URLs. 

Is this expected behavior or is there something I'm doing wrong?

**Comment by gordonnl** [comment]
TextureLoader will cache textures for reuse within OGL (when they have the same texture options), however this has nothing to do with how the browser caches image assets for use elsewhere. 

If you look in the Chrome DevTools Source panel, make sure to uncheck 'disable cache', and then you can usually see how sequential requests for the same asset are served from 'memory cache'. So even though there are multiple requests, you are not re-downloading the image again thanks to the browser. But yeah, nothing to do with OGL.
