### ISSUE TITLE
How to update camera.fov

### ISSUE THREAD

**Issue by ouzhou** [oframe/ogl#94]
need a function like 
```
camera.fov = 20;
camera.updateProjectionMatrix();
```

**Comment by gordonnl** [comment]
You can do eitiher:
```
camera.perspective({ fov: 20 });
```
or
```
camera.fov = 20;
camera.perspective();
```

Please find the related code:
https://github.com/oframe/ogl/blob/2103b389b14af8eb027319a9a2b8a33547b9288f/src/core/Camera.js#L27-L32
