### ISSUE TITLE
Atttribute `id` for geometry

### ISSUE THREAD

**Issue by hansagames** [oframe/ogl#96]
Hi,
in [text](https://github.com/oframe/ogl/blob/master/examples/msdf-text.html) example I saw this `id: { size: 1, data: text.buffers.id },` I tried to check `Geometry` but didnt saw any usage of it, what is purpose of it ? its some built in attribute ?

thank you

**Comment by gordonnl** [comment]
Hi @hansagames,
`id` provides a per-character index, for effects that may require it, such as having text that fades in letter-by-letter.

https://github.com/oframe/ogl/blob/8b4533dfb68a099c11682fc5dada69344348003b/src/extras/Text.js#L49-L50
