### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by hansagames** [oframe/ogl#97]
Hi, I see that it have MIT License in package.json but license file is missing in the root with full license text

**Comment by hansagames** [comment]
I see that it was removed some time ago, any reason for doing that, as there should be full license text anyway with copyright notice

**Comment by gordonnl** [comment]
hm, yeah damn I think you're right. I was thinking that if I note that it is MIT, that obviously refers to the official MIT license wording, so including a copy of it would be redundant. However there is that part about including the license in all copies... if only there was an equivalent without that clause.

**Comment by gordonnl** [comment]
Shoving it in the bottom of the Readme might be a compromise

**Comment by gordonnl** [comment]
Just learnt about the Unlicense - https://choosealicense.com/licenses/unlicense/
Basically MIT without the condition of keeping the license notice!

**Comment by hansagames** [comment]
@gordonnl have a small issue, I am forced to use [license-checker](https://www.npmjs.com/package/license-checker), sadly it have case sensitive check for license names, and name for `unlicense` is `Unlicense `, and now it dont find license for OGL, wanted to fix on their said but project is not very active, would it be possible to change in package.json `"license": "unlicense",` to `"license": "Unlicense",` and release new version on npm ? , otherwise will need to make local patches
