### ISSUE TITLE
Geometry remove function

### ISSUE THREAD

**Issue by hansagames** [oframe/ogl#98]
in geometry remove there is `if (this.vao) this.gl.renderer.deleteVertexArray(this.vao);` could not find `this.vao` anywhere
from where it is set ?

**Comment by gordonnl** [comment]
nice catch, yeah this is outdated since I updated how VAOs were stored. I'll take a look when I have time, cheers!

**Comment by hansagames** [comment]
yes should be like this I suppose 

```typescript
if (this.VAOs) {
            for (let key in this.VAOs) {
                console.log(this.VAOs[key])
                this.gl.renderer.deleteVertexArray(this.VAOs[key]);
                delete this.VAOs[key];
            }
        }
```

**Comment by gordonnl** [comment]
brilliant! If you could please test that I would happily merge a PR! :D

**Comment by hansagames** [comment]
@gordonnl made PR tested on my example, and worked fine, could clear geometry and recreate, if you have some specific test in mind can try that as well

**Comment by hansagames** [comment]
@gordonnl sorry for commenting on closed issue, but would be nice to get npm release, for this

**Comment by gordonnl** [comment]
done! :)
